services:

  postgres1:
    container_name: postgres_keycloak
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
    volumes:
      - ./data/keycloak:/data/postgres
    ports:
      - "5432:5432"
  postgres2:
    container_name: postgres_revolut
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: revolut
    volumes:
      - ./data/revolut:/data/postgres
    ports:
      - "5433:5432"
  postgres3:
    container_name: postgres_conversion
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: conversion
    volumes:
      - ./data/conversion:/data/postgres
    ports:
      - "5434:5432"
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    volumes:
      - ./imports:/opt/jboss/keycloak/imports
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled
    ports:
      - 8082:8080
    depends_on:
      - postgres1

volumes:
  data: