services:

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: banque
    volumes:
      - ./data:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  data: