spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods:
              - GET
      routes:
        - id: conversion-service
          uri: lb://conversion-service/
          predicates:
            - Path=/conversion-service/**
          filters:
            - RewritePath=/conversion-service/(?<path>.*), /$\{path}
        - id: banque
          uri: lb://revolut/
          predicates:
            - Path=/banque/**
          filters:
            - RewritePath=/banque/(?<path>.*), /$\{path}
    loadbalancer:
      ribbon:
        enabled: false
    consul:
      config:
        enabled: false

server:
  port: 8888

