CREATE USER keycloak;
CREATE DATABASE keycloak;
GRANT ALL PRIVILEGES ON DATABASE keycloak TO keycloak;

CREATE USER revolut;
CREATE DATABASE revolut;
GRANT ALL PRIVILEGES ON DATABASE revolut TO revolut;

CREATE USER conversion;
CREATE DATABASE conversion;
GRANT ALL PRIVILEGES ON DATABASE conversion TO conversion;
